server:
  port: 8866

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/febs_cloud_base?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver